// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkGeometryTypeNV](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkGeometryTypeNV.html)
#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkGeometryType {
    Triangles = 0,
    Aabbs = 1,
}

#[doc(hidden)]
pub type RawVkGeometryType = i32;

impl VkWrappedType<RawVkGeometryType> for VkGeometryType {
    fn vk_to_raw(src: &VkGeometryType, dst: &mut RawVkGeometryType) {
        *dst = *src as i32
    }
}

impl VkRawType<VkGeometryType> for RawVkGeometryType {
    fn vk_to_wrapped(src: &RawVkGeometryType) -> VkGeometryType {
        unsafe {
            *((src as *const i32) as *const VkGeometryType)
        }
    }
}

impl Default for VkGeometryType {
    fn default() -> VkGeometryType {
        VkGeometryType::Triangles
    }
}