// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkPipelineViewportSwizzleStateCreateFlagBitsNV](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPipelineViewportSwizzleStateCreateFlagBitsNV.html).
///
/// Use the macro `VkPipelineViewportSwizzleStateCreateFlags!` as an alternative method to create a structure. For example, these two snippets return the same value:
/// ```
/// VkPipelineViewportSwizzleStateCreateFlags!()
/// ```
/// ```
/// VkPipelineViewportSwizzleStateCreateFlags {
/// }
/// ```
#[derive(Debug, Clone)]
pub struct VkPipelineViewportSwizzleStateCreateFlags {
    
}

#[doc(hidden)]
pub type RawVkPipelineViewportSwizzleStateCreateFlags = u32;

impl VkWrappedType<RawVkPipelineViewportSwizzleStateCreateFlags> for VkPipelineViewportSwizzleStateCreateFlags {
    fn vk_to_raw(src: &VkPipelineViewportSwizzleStateCreateFlags, dst: &mut RawVkPipelineViewportSwizzleStateCreateFlags) {
        *dst = 0;
    }
}

impl VkRawType<VkPipelineViewportSwizzleStateCreateFlags> for RawVkPipelineViewportSwizzleStateCreateFlags {
    fn vk_to_wrapped(src: &RawVkPipelineViewportSwizzleStateCreateFlags) -> VkPipelineViewportSwizzleStateCreateFlags {
        VkPipelineViewportSwizzleStateCreateFlags {
            
        }
    }
}

impl Default for VkPipelineViewportSwizzleStateCreateFlags {
    fn default() -> VkPipelineViewportSwizzleStateCreateFlags {
        VkPipelineViewportSwizzleStateCreateFlags {
            
        }
    }
}

impl VkPipelineViewportSwizzleStateCreateFlags {
    
    /// Return a structure with all flags to `false`.
    pub fn none() -> Self {
        VkPipelineViewportSwizzleStateCreateFlags {
            
        }
    }
    
    /// Return a structure with all flags to `true`.
    pub fn all() -> Self {
        VkPipelineViewportSwizzleStateCreateFlags {
            
        }
    }
    
    /// Return the numerical bit flags corresponding to the structure (as described in the Vulkan specs).
    pub fn to_u32(&self) -> u32 {
        0
    }
    
    /// Create a structure corresponding to the specified numerical bit flags.
    pub fn from_u32(value: u32) -> Self {
        VkPipelineViewportSwizzleStateCreateFlags {
            
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! VkPipelineViewportSwizzleStateCreateFlags {
    ( $( $x:ident ),* ) => {
        VkPipelineViewportSwizzleStateCreateFlags {
            $($x: true,)*
            ..VkPipelineViewportSwizzleStateCreateFlags::none()
        }
    }
}