// Generated by `scripts/generate.js`

pub type VkRayTracingShaderGroupType = super::super::khr::VkRayTracingShaderGroupType;

#[doc(hidden)]
pub type RawVkRayTracingShaderGroupType = super::super::khr::RawVkRayTracingShaderGroupType;