// Generated by `scripts/generate.js`

pub type VkBindBufferMemoryInfo<'a, 'b> = super::super::vk::VkBindBufferMemoryInfo<'a, 'b>;

#[doc(hidden)]
pub type RawVkBindBufferMemoryInfo = super::super::vk::RawVkBindBufferMemoryInfo;