// Generated by `scripts/generate.js`

/// Wrapper for [VkBindBufferMemoryInfoKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkBindBufferMemoryInfoKHR.html)
pub type VkBindBufferMemoryInfo<'a, 'b> = super::super::vk::VkBindBufferMemoryInfo<'a, 'b>;

#[doc(hidden)]
pub type RawVkBindBufferMemoryInfo = super::super::vk::RawVkBindBufferMemoryInfo;