// Generated by `scripts/generate.js`

/// Wrapper for [VkDeviceGroupSubmitInfoKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDeviceGroupSubmitInfoKHR.html)
pub type VkDeviceGroupSubmitInfo<'a, 'b, 'c> = super::super::vk::VkDeviceGroupSubmitInfo<'a, 'b, 'c>;

#[doc(hidden)]
pub type RawVkDeviceGroupSubmitInfo = super::super::vk::RawVkDeviceGroupSubmitInfo;