// Generated by `scripts/generate.js`

pub type VkDescriptorUpdateTemplateCreateFlags = super::super::vk::VkDescriptorUpdateTemplateCreateFlags;

#[doc(hidden)]
pub type RawVkDescriptorUpdateTemplateCreateFlags = super::super::vk::RawVkDescriptorUpdateTemplateCreateFlags;