// Generated by `scripts/generate.js`

pub type VkDeviceGroupDeviceCreateInfo<'a, 'b> = super::super::vk::VkDeviceGroupDeviceCreateInfo<'a, 'b>;

#[doc(hidden)]
pub type RawVkDeviceGroupDeviceCreateInfo = super::super::vk::RawVkDeviceGroupDeviceCreateInfo;