// Generated by `scripts/generate.js`

pub type VkDescriptorUpdateTemplateType = super::super::vk::VkDescriptorUpdateTemplateType;

pub type RawVkDescriptorUpdateTemplateType = super::super::vk::RawVkDescriptorUpdateTemplateType;