// Generated by `scripts/generate.js`

pub type VkDeviceGroupSubmitInfo<'a, 'b, 'c> = super::super::vk::VkDeviceGroupSubmitInfo<'a, 'b, 'c>;

pub type RawVkDeviceGroupSubmitInfo = super::super::vk::RawVkDeviceGroupSubmitInfo;