// Generated by `scripts/generate.js`

pub type VkExternalSemaphoreFeatureFlags = super::super::vk::VkExternalSemaphoreFeatureFlags;

pub type RawVkExternalSemaphoreFeatureFlags = super::super::vk::RawVkExternalSemaphoreFeatureFlags;