// Generated by `scripts/generate.js`

pub type VkExportMemoryAllocateInfo = super::super::vk::VkExportMemoryAllocateInfo;

pub type RawVkExportMemoryAllocateInfo = super::super::vk::RawVkExportMemoryAllocateInfo;