// Generated by `scripts/generate.js`

pub type VkExternalFenceFeatureFlags = super::super::vk::VkExternalFenceFeatureFlags;

#[doc(hidden)]
pub type RawVkExternalFenceFeatureFlags = super::super::vk::RawVkExternalFenceFeatureFlags;