// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};
use vulkan::khr::{VkSwapchain,RawVkSwapchain};

/// Wrapper for [VkImageSwapchainCreateInfoKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkImageSwapchainCreateInfoKHR.html).
#[derive(Debug, Clone)]
pub struct VkImageSwapchainCreateInfo {
    pub swapchain: VkSwapchain,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkImageSwapchainCreateInfo {
    pub s_type: RawVkStructureType,
    pub next: *mut c_void,
    pub swapchain: RawVkSwapchain,
}

impl VkWrappedType<RawVkImageSwapchainCreateInfo> for VkImageSwapchainCreateInfo {
    fn vk_to_raw(src: &VkImageSwapchainCreateInfo, dst: &mut RawVkImageSwapchainCreateInfo) {
        dst.s_type = vk_to_raw_value(&VkStructureType::ImageSwapchainCreateInfoKhr);
        dst.next = ptr::null_mut();
        dst.swapchain = vk_to_raw_value(&src.swapchain);
    }
}

impl VkRawType<VkImageSwapchainCreateInfo> for RawVkImageSwapchainCreateInfo {
    fn vk_to_wrapped(src: &RawVkImageSwapchainCreateInfo) -> VkImageSwapchainCreateInfo {
        VkImageSwapchainCreateInfo {
            swapchain: RawVkSwapchain::vk_to_wrapped(&src.swapchain),
        }
    }
}

impl Default for VkImageSwapchainCreateInfo {
    fn default() -> VkImageSwapchainCreateInfo {
        VkImageSwapchainCreateInfo {
            swapchain: Default::default(),
        }
    }
}

impl VkSetup for VkImageSwapchainCreateInfo {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        VkSetup::vk_setup(&mut self.swapchain, fn_table);
    }
}

impl VkFree for RawVkImageSwapchainCreateInfo {
    fn vk_free(&self) {
        
    }
}