// Generated by `scripts/generate.js`

/// Wrapper for [VkPhysicalDeviceGroupPropertiesKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceGroupPropertiesKHR.html)
pub type VkPhysicalDeviceGroupProperties = super::super::vk::VkPhysicalDeviceGroupProperties;

#[doc(hidden)]
pub type RawVkPhysicalDeviceGroupProperties = super::super::vk::RawVkPhysicalDeviceGroupProperties;