// Generated by `scripts/generate.js`

pub type VkPointClippingBehavior = super::super::vk::VkPointClippingBehavior;

#[doc(hidden)]
pub type RawVkPointClippingBehavior = super::super::vk::RawVkPointClippingBehavior;