// Generated by `scripts/generate.js`

pub type VkPhysicalDeviceFloatControlsProperties = super::super::vk::VkPhysicalDeviceFloatControlsProperties;

#[doc(hidden)]
pub type RawVkPhysicalDeviceFloatControlsProperties = super::super::vk::RawVkPhysicalDeviceFloatControlsProperties;