// Generated by `scripts/generate.js`

pub type VkPhysicalDeviceVariablePointerFeatures = super::super::vk::VkPhysicalDeviceVariablePointersFeatures;

#[doc(hidden)]
pub type RawVkPhysicalDeviceVariablePointerFeatures = super::super::vk::RawVkPhysicalDeviceVariablePointersFeatures;