// Generated by `scripts/generate.js`

/// Wrapper for [VkPhysicalDeviceIDPropertiesKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceIDPropertiesKHR.html)
pub type VkPhysicalDeviceIDProperties = super::super::vk::VkPhysicalDeviceIDProperties;

#[doc(hidden)]
pub type RawVkPhysicalDeviceIDProperties = super::super::vk::RawVkPhysicalDeviceIDProperties;