// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};

/// Wrapper for [VkPhysicalDevicePerformanceQueryPropertiesKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDevicePerformanceQueryPropertiesKHR.html).
#[derive(Debug, Clone)]
pub struct VkPhysicalDevicePerformanceQueryProperties {
    pub allow_command_buffer_query_copies: bool,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkPhysicalDevicePerformanceQueryProperties {
    pub s_type: RawVkStructureType,
    pub next: *mut c_void,
    pub allow_command_buffer_query_copies: u32,
}

impl VkWrappedType<RawVkPhysicalDevicePerformanceQueryProperties> for VkPhysicalDevicePerformanceQueryProperties {
    fn vk_to_raw(src: &VkPhysicalDevicePerformanceQueryProperties, dst: &mut RawVkPhysicalDevicePerformanceQueryProperties) {
        dst.s_type = vk_to_raw_value(&VkStructureType::PhysicalDevicePerformanceQueryPropertiesKhr);
        dst.next = ptr::null_mut();
        dst.allow_command_buffer_query_copies = vk_to_raw_value(&src.allow_command_buffer_query_copies);
    }
}

impl VkRawType<VkPhysicalDevicePerformanceQueryProperties> for RawVkPhysicalDevicePerformanceQueryProperties {
    fn vk_to_wrapped(src: &RawVkPhysicalDevicePerformanceQueryProperties) -> VkPhysicalDevicePerformanceQueryProperties {
        VkPhysicalDevicePerformanceQueryProperties {
            allow_command_buffer_query_copies: u32::vk_to_wrapped(&src.allow_command_buffer_query_copies),
        }
    }
}

impl Default for VkPhysicalDevicePerformanceQueryProperties {
    fn default() -> VkPhysicalDevicePerformanceQueryProperties {
        VkPhysicalDevicePerformanceQueryProperties {
            allow_command_buffer_query_copies: false,
        }
    }
}

impl VkSetup for VkPhysicalDevicePerformanceQueryProperties {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkPhysicalDevicePerformanceQueryProperties {
    fn vk_free(&self) {
        
    }
}