// Generated by `scripts/generate.js`

/// Wrapper for [VkPhysicalDeviceMultiviewFeaturesKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceMultiviewFeaturesKHR.html)
pub type VkPhysicalDeviceMultiviewFeatures = super::super::vk::VkPhysicalDeviceMultiviewFeatures;

#[doc(hidden)]
pub type RawVkPhysicalDeviceMultiviewFeatures = super::super::vk::RawVkPhysicalDeviceMultiviewFeatures;