// Generated by `scripts/generate.js`

pub type VkPhysicalDeviceTimelineSemaphoreFeatures = super::super::vk::VkPhysicalDeviceTimelineSemaphoreFeatures;

#[doc(hidden)]
pub type RawVkPhysicalDeviceTimelineSemaphoreFeatures = super::super::vk::RawVkPhysicalDeviceTimelineSemaphoreFeatures;