// Generated by `scripts/generate.js`

/// Wrapper for [VkQueueFamilyProperties2KHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkQueueFamilyProperties2KHR.html)
pub type VkQueueFamilyProperties2 = super::super::vk::VkQueueFamilyProperties2;

#[doc(hidden)]
pub type RawVkQueueFamilyProperties2 = super::super::vk::RawVkQueueFamilyProperties2;