// Generated by `scripts/generate.js`

/// Wrapper for [VkSamplerYcbcrConversionCreateInfoKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSamplerYcbcrConversionCreateInfoKHR.html)
pub type VkSamplerYcbcrConversionCreateInfo = super::super::vk::VkSamplerYcbcrConversionCreateInfo;

#[doc(hidden)]
pub type RawVkSamplerYcbcrConversionCreateInfo = super::super::vk::RawVkSamplerYcbcrConversionCreateInfo;