// Generated by `scripts/generate.js`

/// Wrapper for [VkSparseImageMemoryRequirements2KHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSparseImageMemoryRequirements2KHR.html)
pub type VkSparseImageMemoryRequirements2 = super::super::vk::VkSparseImageMemoryRequirements2;

#[doc(hidden)]
pub type RawVkSparseImageMemoryRequirements2 = super::super::vk::RawVkSparseImageMemoryRequirements2;