// Generated by `scripts/generate.js`

/// Wrapper for [VkSparseImageFormatProperties2KHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSparseImageFormatProperties2KHR.html)
pub type VkSparseImageFormatProperties2 = super::super::vk::VkSparseImageFormatProperties2;

#[doc(hidden)]
pub type RawVkSparseImageFormatProperties2 = super::super::vk::RawVkSparseImageFormatProperties2;