// Generated by `scripts/generate.js`

/// Wrapper for [VkSamplerYcbcrConversionKHR](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSamplerYcbcrConversionKHR.html)
pub type VkSamplerYcbcrConversion = super::super::vk::VkSamplerYcbcrConversion;

#[doc(hidden)]
pub type RawVkSamplerYcbcrConversion = super::super::vk::RawVkSamplerYcbcrConversion;