// Generated by `scripts/generate.js`

pub type VkTessellationDomainOrigin = super::super::vk::VkTessellationDomainOrigin;

#[doc(hidden)]
pub type RawVkTessellationDomainOrigin = super::super::vk::RawVkTessellationDomainOrigin;