// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkObjectEntryUsageFlagsNVX](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkObjectEntryUsageFlagsNVX.html).
///
/// Use the macro `VkObjectEntryUsageFlags!` as an alternative method to create a structure. For example, these two snippets return the same value:
/// ```
/// VkObjectEntryUsageFlags!(graphics, compute)
/// ```
/// ```
/// VkObjectEntryUsageFlags {
///     graphics: true,
///     compute: true,
/// }
/// ```
#[derive(Debug, Clone)]
pub struct VkObjectEntryUsageFlags {
    pub graphics: bool,
    pub compute: bool,
}

#[doc(hidden)]
pub type RawVkObjectEntryUsageFlags = u32;

impl VkWrappedType<RawVkObjectEntryUsageFlags> for VkObjectEntryUsageFlags {
    fn vk_to_raw(src: &VkObjectEntryUsageFlags, dst: &mut RawVkObjectEntryUsageFlags) {
        *dst = 0;
        if src.graphics { *dst |= 0x00000001; }
        if src.compute { *dst |= 0x00000002; }
    }
}

impl VkRawType<VkObjectEntryUsageFlags> for RawVkObjectEntryUsageFlags {
    fn vk_to_wrapped(src: &RawVkObjectEntryUsageFlags) -> VkObjectEntryUsageFlags {
        VkObjectEntryUsageFlags {
            graphics: (src & 0x00000001) != 0,
            compute: (src & 0x00000002) != 0,
        }
    }
}

impl Default for VkObjectEntryUsageFlags {
    fn default() -> VkObjectEntryUsageFlags {
        VkObjectEntryUsageFlags {
            graphics: false,
            compute: false,
        }
    }
}

impl VkObjectEntryUsageFlags {
    
    /// Return a structure with all flags to `false`.
    pub fn none() -> Self {
        VkObjectEntryUsageFlags {
            graphics: false,
            compute: false,
        }
    }
    
    /// Return a structure with all flags to `true`.
    pub fn all() -> Self {
        VkObjectEntryUsageFlags {
            graphics: true,
            compute: true,
        }
    }
    
    /// Return the numerical bit flags corresponding to the structure (as described in the Vulkan specs).
    pub fn to_u32(&self) -> u32 {
        0
        + if self.graphics { 0x00000001 } else { 0 }
        + if self.compute { 0x00000002 } else { 0 }
    }
    
    /// Create a structure corresponding to the specified numerical bit flags.
    pub fn from_u32(value: u32) -> Self {
        VkObjectEntryUsageFlags {
            graphics: value & 0x00000001 > 0,
            compute: value & 0x00000002 > 0,
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! VkObjectEntryUsageFlags {
    ( $( $x:ident ),* ) => {
        VkObjectEntryUsageFlags {
            $($x: true,)*
            ..VkObjectEntryUsageFlags::none()
        }
    }
}