// Generated by `scripts/generate_vk.js`

use utils::vk_traits::*;

#[derive(Debug, Clone, Copy)]
pub struct VkSwapchainCreateFlags {
    pub split_instance_bind_regions: bool,
    pub protected: bool,
    pub mutable_format: bool,
}

pub type RawVkSwapchainCreateFlags = u32;

impl VkWrappedType<RawVkSwapchainCreateFlags> for VkSwapchainCreateFlags {
    fn vk_to_raw(src: &VkSwapchainCreateFlags, dst: &mut RawVkSwapchainCreateFlags) {
        *dst = 0;
        if src.split_instance_bind_regions { *dst |= 0x00000001; }
        if src.protected { *dst |= 0x00000002; }
        if src.mutable_format { *dst |= 0x00000004; }
    }
}

impl VkRawType<VkSwapchainCreateFlags> for RawVkSwapchainCreateFlags {
    fn vk_to_wrapped(src: &RawVkSwapchainCreateFlags) -> VkSwapchainCreateFlags {
        VkSwapchainCreateFlags {
            split_instance_bind_regions: (src & 0x00000001) != 0,
            protected: (src & 0x00000002) != 0,
            mutable_format: (src & 0x00000004) != 0,
        }
    }
}

impl Default for VkSwapchainCreateFlags {
    fn default() -> VkSwapchainCreateFlags {
        VkSwapchainCreateFlags {
            split_instance_bind_regions: false,
            protected: false,
            mutable_format: false,
        }
    }
}

impl VkSwapchainCreateFlags {
    
    pub fn none() -> VkSwapchainCreateFlags {
        VkSwapchainCreateFlags {
            split_instance_bind_regions: false,
            protected: false,
            mutable_format: false,
        }
    }
    
    pub fn all() -> VkSwapchainCreateFlags {
        VkSwapchainCreateFlags {
            split_instance_bind_regions: true,
            protected: true,
            mutable_format: true,
        }
    }
}

impl VkSwapchainCreateFlags {
    
    pub fn to_u32(&self) -> u32 {
        0
        + if self.split_instance_bind_regions { 0x00000001 } else { 0 }
        + if self.protected { 0x00000002 } else { 0 }
        + if self.mutable_format { 0x00000004 } else { 0 }
    }
}