// Generated by `scripts/generate_vk.js`

use utils::vk_type::*;

pub type RawVkAttachmentDescriptionFlags = u32;

#[derive(Debug, Copy, Clone)]
pub struct VkAttachmentDescriptionFlags {
    may_alias: bool,
}

impl VkRawType<VkAttachmentDescriptionFlags> for RawVkAttachmentDescriptionFlags {
    fn vk_to_wrapped(src: &RawVkAttachmentDescriptionFlags) -> VkAttachmentDescriptionFlags {
        VkAttachmentDescriptionFlags {
            may_alias: (src & 0x00000001) != 0,
        }
    }
}

impl VkWrappedType<RawVkAttachmentDescriptionFlags> for VkAttachmentDescriptionFlags {
    fn vk_to_raw(src: &VkAttachmentDescriptionFlags, dst: &mut RawVkAttachmentDescriptionFlags) {
        *dst = 0;
        if src.may_alias { *dst |= 0x00000001; }
    }
}

pub static STATIC_VK_ATTACHMENT_DESCRIPTION_FLAGS : VkAttachmentDescriptionFlags = VkAttachmentDescriptionFlags {
    may_alias: false,
};

impl VkDefault for VkAttachmentDescriptionFlags {
    fn vk_default() -> VkAttachmentDescriptionFlags {
        STATIC_VK_ATTACHMENT_DESCRIPTION_FLAGS
    }
}