// Generated by `scripts/generate_vk.js`

use utils::vk_traits::*;

#[derive(Debug, Clone, Copy)]
pub struct VkBufferViewCreateFlags {
    
}

pub type RawVkBufferViewCreateFlags = u32;

impl VkWrappedType<RawVkBufferViewCreateFlags> for VkBufferViewCreateFlags {
    fn vk_to_raw(src: &VkBufferViewCreateFlags, dst: &mut RawVkBufferViewCreateFlags) {
        *dst = 0;
    }
}

impl VkRawType<VkBufferViewCreateFlags> for RawVkBufferViewCreateFlags {
    fn vk_to_wrapped(src: &RawVkBufferViewCreateFlags) -> VkBufferViewCreateFlags {
        VkBufferViewCreateFlags {
            
        }
    }
}

impl Default for VkBufferViewCreateFlags {
    fn default() -> VkBufferViewCreateFlags {
        VkBufferViewCreateFlags {
            
        }
    }
}

impl VkBufferViewCreateFlags {
    
    pub fn none() -> VkBufferViewCreateFlags {
        VkBufferViewCreateFlags {
            
        }
    }
    
    pub fn all() -> VkBufferViewCreateFlags {
        VkBufferViewCreateFlags {
            
        }
    }
}

impl VkBufferViewCreateFlags {
    
    pub fn to_u32(&self) -> u32 {
        0
    }
}