// Generated by `scripts/generate_vk.js`

use vk::*;
use std::os::raw::c_char;

pub type RawVkBool32 = u32;

pub type VkBool32 = bool;

impl VkFrom<VkBool32> for RawVkBool32 {
    
    fn vk_from(value: &VkBool32) -> Self {
        if *value { 1 } else { 0 }
    }
}

impl VkFrom<RawVkBool32> for VkBool32 {
    
    fn vk_from(value: &RawVkBool32) -> Self {
        *value != 0
    }
}