// Generated by `scripts/generate_vk.js`

use utils::vk_traits::*;

pub type RawVkFrontFace = i32;

#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkFrontFace {
    CounterClockwise = 0,
    Clockwise = 1,
}

impl VkRawType<VkFrontFace> for RawVkFrontFace {
    fn vk_to_wrapped(src: &RawVkFrontFace) -> VkFrontFace {
        unsafe {
            *((src as *const i32) as *const VkFrontFace)
        }
    }
}

impl VkWrappedType<RawVkFrontFace> for VkFrontFace {
    fn vk_to_raw(src: &VkFrontFace, dst: &mut RawVkFrontFace) {
        *dst = *src as i32
    }
}

impl Default for VkFrontFace {
    fn default() -> VkFrontFace {
        VkFrontFace::CounterClockwise
    }
}