// Generated by `scripts/generate_vk.js`

use utils::vk_traits::*;

pub type RawVkMemoryMapFlags = u32;

#[derive(Debug, Clone, Copy)]
pub struct VkMemoryMapFlags {
    
}

impl VkRawType<VkMemoryMapFlags> for RawVkMemoryMapFlags {
    fn vk_to_wrapped(src: &RawVkMemoryMapFlags) -> VkMemoryMapFlags {
        VkMemoryMapFlags {
            
        }
    }
}

impl VkWrappedType<RawVkMemoryMapFlags> for VkMemoryMapFlags {
    fn vk_to_raw(src: &VkMemoryMapFlags, dst: &mut RawVkMemoryMapFlags) {
        *dst = 0;
    }
}

impl Default for VkMemoryMapFlags {
    fn default() -> VkMemoryMapFlags {
        VkMemoryMapFlags {
            
        }
    }
}

impl VkMemoryMapFlags {
    
    pub fn none() -> VkMemoryMapFlags {
        VkMemoryMapFlags {
            
        }
    }
    
    pub fn all() -> VkMemoryMapFlags {
        VkMemoryMapFlags {
            
        }
    }
}