// Generated by `scripts/generate_type.js`

use std::convert::From;
use std::default::Default;

pub type RawVkPresentMode = i32;



#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkPresentMode {
    Immediate = 0,
    Mailbox = 1,
    Fifo = 2,
    FifoRelaxed = 3,
    SharedDemandRefresh = 1000111000,
    SharedContinuousRefresh = 1000111001
}

impl<'a> From<&'a i32> for VkPresentMode {
    fn from(value: &'a i32) -> Self {
        unsafe { *((value as *const i32) as *const VkPresentMode) }
    }
}

impl<'a> From<&'a VkPresentMode> for i32 {
    fn from(value: &'a VkPresentMode) -> Self {
        *value as i32
    }
}