// Generated by `scripts/generate.js`

use utils::vk_traits::*;

#[derive(Debug, Clone, Copy)]
pub struct VkPipelineTessellationStateCreateFlags {
    
}

pub type RawVkPipelineTessellationStateCreateFlags = u32;

impl VkWrappedType<RawVkPipelineTessellationStateCreateFlags> for VkPipelineTessellationStateCreateFlags {
    fn vk_to_raw(src: &VkPipelineTessellationStateCreateFlags, dst: &mut RawVkPipelineTessellationStateCreateFlags) {
        *dst = 0;
    }
}

impl VkRawType<VkPipelineTessellationStateCreateFlags> for RawVkPipelineTessellationStateCreateFlags {
    fn vk_to_wrapped(src: &RawVkPipelineTessellationStateCreateFlags) -> VkPipelineTessellationStateCreateFlags {
        VkPipelineTessellationStateCreateFlags {
            
        }
    }
}

impl Default for VkPipelineTessellationStateCreateFlags {
    fn default() -> VkPipelineTessellationStateCreateFlags {
        VkPipelineTessellationStateCreateFlags {
            
        }
    }
}

impl VkPipelineTessellationStateCreateFlags {
    
    pub fn none() -> VkPipelineTessellationStateCreateFlags {
        VkPipelineTessellationStateCreateFlags {
            
        }
    }
    
    pub fn all() -> VkPipelineTessellationStateCreateFlags {
        VkPipelineTessellationStateCreateFlags {
            
        }
    }
}

#[macro_export]
macro_rules! VkPipelineTessellationStateCreateFlags {
    ( $( $x:ident ),* ) => {
        VkPipelineTessellationStateCreateFlags {
            $($x: true,)*
            ..VkPipelineTessellationStateCreateFlags::none()
        }
    }
}

impl VkPipelineTessellationStateCreateFlags {
    
    pub fn to_u32(&self) -> u32 {
        0
    }
}