// Generated by `scripts/generate_vk.js`

use utils::vk_traits::*;

pub type RawVkPipelineRasterizationStateCreateFlags = u32;

#[derive(Debug, Clone, Copy)]
pub struct VkPipelineRasterizationStateCreateFlags {
    
}

impl VkRawType<VkPipelineRasterizationStateCreateFlags> for RawVkPipelineRasterizationStateCreateFlags {
    fn vk_to_wrapped(src: &RawVkPipelineRasterizationStateCreateFlags) -> VkPipelineRasterizationStateCreateFlags {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
}

impl VkWrappedType<RawVkPipelineRasterizationStateCreateFlags> for VkPipelineRasterizationStateCreateFlags {
    fn vk_to_raw(src: &VkPipelineRasterizationStateCreateFlags, dst: &mut RawVkPipelineRasterizationStateCreateFlags) {
        *dst = 0;
    }
}

impl Default for VkPipelineRasterizationStateCreateFlags {
    fn default() -> VkPipelineRasterizationStateCreateFlags {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
}

impl VkPipelineRasterizationStateCreateFlags {
    
    pub fn none() -> VkPipelineRasterizationStateCreateFlags {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
    
    pub fn all() -> VkPipelineRasterizationStateCreateFlags {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
}