// Generated by `scripts/generate_vk.js`

use utils::vk_type::*;

pub type RawVkPipelineDynamicStateCreateFlags = u32;

#[derive(Debug, Copy, Clone)]
pub struct VkPipelineDynamicStateCreateFlags {
    
}

impl VkRawType<VkPipelineDynamicStateCreateFlags> for RawVkPipelineDynamicStateCreateFlags {
    fn vk_to_wrapped(src: &RawVkPipelineDynamicStateCreateFlags) -> VkPipelineDynamicStateCreateFlags {
        VkPipelineDynamicStateCreateFlags {
            
        }
    }
}

impl VkWrappedType<RawVkPipelineDynamicStateCreateFlags> for VkPipelineDynamicStateCreateFlags {
    fn vk_to_raw(src: &VkPipelineDynamicStateCreateFlags, dst: &mut RawVkPipelineDynamicStateCreateFlags) {
        *dst = 0;
    }
}

pub static STATIC_VK_PIPELINE_DYNAMIC_STATE_CREATE_FLAGS : VkPipelineDynamicStateCreateFlags = VkPipelineDynamicStateCreateFlags {
    
};

impl VkDefault for VkPipelineDynamicStateCreateFlags {
    fn vk_default() -> VkPipelineDynamicStateCreateFlags {
        STATIC_VK_PIPELINE_DYNAMIC_STATE_CREATE_FLAGS
    }
}