// Generated by `scripts/generate_vk.js`

use utils::vk_type::VkType;

pub type RawVkPhysicalDeviceType = i32;

#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkPhysicalDeviceType {
    Other = 0,
    IntegratedGpu = 1,
    DiscreteGpu = 2,
    VirtualGpu = 3,
    Cpu = 4,
}

impl VkType<RawVkPhysicalDeviceType> for VkPhysicalDeviceType {
    
    fn vk_to_raw(src: &VkPhysicalDeviceType, dst: &mut RawVkPhysicalDeviceType) {
        *dst = *src as i32
    }
    
    fn vk_from_raw(src: &RawVkPhysicalDeviceType) -> VkPhysicalDeviceType {
        unsafe {
            *((src as *const i32) as *const VkPhysicalDeviceType)
        }
    }
    
    fn vk_default() -> VkPhysicalDeviceType {
        VkPhysicalDeviceType::Other
    }
}