// Generated by `scripts/generate_vk.js`

use utils::vk_type::VkType;

pub type RawVkQueryType = i32;

#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkQueryType {
    Occlusion = 0,
    PipelineStatistics = 1,
    Timestamp = 2,
}

impl VkType<RawVkQueryType> for VkQueryType {
    
    fn vk_to_raw(src: &VkQueryType, dst: &mut RawVkQueryType) {
        *dst = *src as i32
    }
    
    fn vk_from_raw(src: &RawVkQueryType) -> VkQueryType {
        unsafe {
            *((src as *const i32) as *const VkQueryType)
        }
    }
    
    fn vk_default() -> VkQueryType {
        VkQueryType::Occlusion
    }
}