// Generated by `scripts/generate_vk.js`

use vk::*;
use std::os::raw::c_char;
use std::ptr::null;
use libc::*;

#[repr(C)]
pub struct RawVkSurfaceFormat {
    format: RawVkFormat,
    color_space: RawVkColorSpace,
}

#[derive(Debug)]
pub struct VkSurfaceFormat {
    pub format: VkFormat,
    pub color_space: VkColorSpace,
}

impl VkFrom<VkSurfaceFormat> for RawVkSurfaceFormat {
    
    fn vk_from(value: &VkSurfaceFormat) -> Self {
        Self {
            format: VkFrom::vk_from(&value.format),
            color_space: VkFrom::vk_from(&value.color_space),
        }
    }
}

impl VkFrom<RawVkSurfaceFormat> for VkSurfaceFormat {
    
    fn vk_from(value: &RawVkSurfaceFormat) -> Self {
        Self {
            format: VkFrom::vk_from(&value.format),
            color_space: VkFrom::vk_from(&value.color_space),
        }
    }
}