// Generated by `scripts/generate_vk.js`

use vk::*;
use std::os::raw::c_char;
use std::ops::Drop;
use std::vec::Vec;
use std::ptr::null;
use libc::c_void;
use glfw::*;

pub type RawVkSwapchainKHR = RawVkHandle;

#[derive(Debug)]
pub struct VkSwapchainKHR {
    _handle: RawVkSwapchainKHR,
    _device: RawVkDevice,
}

impl VkSwapchainKHR {
    
    pub fn handle(&self) -> RawVkSwapchainKHR {
        self._handle
    }
    
    pub fn new(device: &VkDevice, create_info: &VkSwapchainCreateInfoKHR) -> Result<VkSwapchainKHR, VkResult> {
        unsafe {
            let device_handle = device.handle();
            let mut raw_create_info = RawVkSwapchainCreateInfoKHR::vk_from(create_info);
            let raw_create_info_ptr = &mut raw_create_info as *mut RawVkSwapchainCreateInfoKHR;
            vk_call_retrieve_single(
                |ptr| vkCreateSwapchainKHR(device_handle, raw_create_info_ptr, null(), ptr),
                |swapchain_khr : &mut VkSwapchainKHR| { swapchain_khr._device = device_handle; }
            )
        }
    }
    
    pub fn get_images(&self) -> Result<Vec<VkImage>, VkResult> {
        unsafe {
            vk_call_retrieve_list(
                |count, ptr| vkGetSwapchainImagesKHR(self._device, self._handle, count, ptr),
                |image : &mut VkImage| {  }
            )
        }
    }
}

impl VkFrom<VkSwapchainKHR> for RawVkSwapchainKHR {
    
    fn vk_from(value: &VkSwapchainKHR) -> Self {
        value._handle
    }
}

impl VkFrom<RawVkSwapchainKHR> for VkSwapchainKHR {
    
    fn vk_from(value: &RawVkSwapchainKHR) -> Self {
        Self {
            _handle: *value,
            _device: VK_NULL_HANDLE,
        }
    }
}

impl Drop for VkSwapchainKHR {
    
    fn drop(&mut self) {
        unsafe {
            vkDestroySwapchainKHR(self._device, self._handle, null());
        }
    }
}

extern {
    fn vkDestroySwapchainKHR(device: RawVkDevice, swapchain: RawVkSwapchainKHR, p_allocator: *const c_void);
    fn vkCreateSwapchainKHR(device: RawVkDevice, p_create_info: *const RawVkSwapchainCreateInfoKHR, p_allocator: *const c_void, p_swapchain: *mut RawVkSwapchainKHR)-> RawVkResult;
    fn vkGetSwapchainImagesKHR(device: RawVkDevice, swapchain: RawVkSwapchainKHR, p_swapchain_image_count: *mut u32, p_swapchain_images: *mut RawVkImage)-> RawVkResult;
}