// Generated by `scripts/generate_vk.js`

use utils::vk_type::*;

pub type RawVkSparseMemoryBindFlags = u32;

#[derive(Debug, Copy, Clone)]
pub struct VkSparseMemoryBindFlags {
    metadata: bool,
}

impl VkRawType<VkSparseMemoryBindFlags> for RawVkSparseMemoryBindFlags {
    
    fn vk_to_wrapped(src: &RawVkSparseMemoryBindFlags) -> VkSparseMemoryBindFlags {
        VkSparseMemoryBindFlags {
            metadata: (src & 0x00000001) != 0,
        }
    }
}

impl VkWrappedType<RawVkSparseMemoryBindFlags> for VkSparseMemoryBindFlags {
    
    fn vk_to_raw(src: &VkSparseMemoryBindFlags, dst: &mut RawVkSparseMemoryBindFlags) {
        *dst = 0;
        if src.metadata { *dst |= 0x00000001; }
    }
    
    fn vk_default() -> VkSparseMemoryBindFlags {
        VkSparseMemoryBindFlags {
            metadata: false,
        }
    }
}