// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkDebugUtilsMessengerCreateFlagsEXT](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDebugUtilsMessengerCreateFlagsEXT.html).
///
/// Use the macro `VkDebugUtilsMessengerCreateFlags!` as an alternative method to create a structure. For example, these two snippets return the same value:
/// ```
/// VkDebugUtilsMessengerCreateFlags!()
/// ```
/// ```
/// VkDebugUtilsMessengerCreateFlags {
/// }
/// ```
#[derive(Debug, Clone)]
pub struct VkDebugUtilsMessengerCreateFlags {
    
}

#[doc(hidden)]
pub type RawVkDebugUtilsMessengerCreateFlags = u32;

impl VkWrappedType<RawVkDebugUtilsMessengerCreateFlags> for VkDebugUtilsMessengerCreateFlags {
    fn vk_to_raw(src: &VkDebugUtilsMessengerCreateFlags, dst: &mut RawVkDebugUtilsMessengerCreateFlags) {
        *dst = 0;
    }
}

impl VkRawType<VkDebugUtilsMessengerCreateFlags> for RawVkDebugUtilsMessengerCreateFlags {
    fn vk_to_wrapped(src: &RawVkDebugUtilsMessengerCreateFlags) -> VkDebugUtilsMessengerCreateFlags {
        VkDebugUtilsMessengerCreateFlags {
            
        }
    }
}

impl Default for VkDebugUtilsMessengerCreateFlags {
    fn default() -> VkDebugUtilsMessengerCreateFlags {
        VkDebugUtilsMessengerCreateFlags {
            
        }
    }
}

impl VkDebugUtilsMessengerCreateFlags {
    
    /// Return a structure with all flags to `false`.
    pub fn none() -> Self {
        VkDebugUtilsMessengerCreateFlags {
            
        }
    }
    
    /// Return a structure with all flags to `true`.
    pub fn all() -> Self {
        VkDebugUtilsMessengerCreateFlags {
            
        }
    }
    
    /// Return the numerical bit flags corresponding to the structure (as described in the Vulkan specs).
    pub fn to_u32(&self) -> u32 {
        0
    }
    
    /// Create a structure corresponding to the specified numerical bit flags.
    pub fn from_u32(value: u32) -> Self {
        VkDebugUtilsMessengerCreateFlags {
            
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! VkDebugUtilsMessengerCreateFlags {
    ( $( $x:ident ),* ) => {
        VkDebugUtilsMessengerCreateFlags {
            $($x: true,)*
            ..VkDebugUtilsMessengerCreateFlags::none()
        }
    }
}