// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};
use vulkan::ext::{VkDebugReportObjectType,RawVkDebugReportObjectType};

/// Wrapper for [VkDebugMarkerObjectNameInfoEXT](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDebugMarkerObjectNameInfoEXT.html).
#[derive(Debug, Clone)]
pub struct VkDebugMarkerObjectNameInfo {
    pub object_type: VkDebugReportObjectType,
    pub object: usize,
    pub object_name: String,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkDebugMarkerObjectNameInfo {
    pub s_type: RawVkStructureType,
    pub next: *const c_void,
    pub object_type: RawVkDebugReportObjectType,
    pub object: u64,
    pub object_name: *const c_char,
}

impl VkWrappedType<RawVkDebugMarkerObjectNameInfo> for VkDebugMarkerObjectNameInfo {
    fn vk_to_raw(src: &VkDebugMarkerObjectNameInfo, dst: &mut RawVkDebugMarkerObjectNameInfo) {
        dst.s_type = vk_to_raw_value(&VkStructureType::DebugMarkerObjectNameInfoExt);
        dst.next = ptr::null();
        dst.object_type = vk_to_raw_value(&src.object_type);
        dst.object = vk_to_raw_value(&src.object);
        dst.object_name = new_ptr_string(&src.object_name);
    }
}

impl VkRawType<VkDebugMarkerObjectNameInfo> for RawVkDebugMarkerObjectNameInfo {
    fn vk_to_wrapped(src: &RawVkDebugMarkerObjectNameInfo) -> VkDebugMarkerObjectNameInfo {
        VkDebugMarkerObjectNameInfo {
            object_type: RawVkDebugReportObjectType::vk_to_wrapped(&src.object_type),
            object: u64::vk_to_wrapped(&src.object),
            object_name: new_string(src.object_name),
        }
    }
}

impl Default for VkDebugMarkerObjectNameInfo {
    fn default() -> VkDebugMarkerObjectNameInfo {
        VkDebugMarkerObjectNameInfo {
            object_type: Default::default(),
            object: 0,
            object_name: String::new(),
        }
    }
}

impl VkSetup for VkDebugMarkerObjectNameInfo {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkDebugMarkerObjectNameInfo {
    fn vk_free(&self) {
        free_ptr(self.object_name);
    }
}