// Generated by `scripts/generate.js`

pub type VkDescriptorSetVariableDescriptorCountLayoutSupport = super::super::vk::VkDescriptorSetVariableDescriptorCountLayoutSupport;

#[doc(hidden)]
pub type RawVkDescriptorSetVariableDescriptorCountLayoutSupport = super::super::vk::RawVkDescriptorSetVariableDescriptorCountLayoutSupport;