// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};

/// Wrapper for [VkMemoryPriorityAllocateInfoEXT](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkMemoryPriorityAllocateInfoEXT.html).
#[derive(Debug, Clone)]
pub struct VkMemoryPriorityAllocateInfo {
    pub priority: f32,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkMemoryPriorityAllocateInfo {
    pub s_type: RawVkStructureType,
    pub next: *mut c_void,
    pub priority: f32,
}

impl VkWrappedType<RawVkMemoryPriorityAllocateInfo> for VkMemoryPriorityAllocateInfo {
    fn vk_to_raw(src: &VkMemoryPriorityAllocateInfo, dst: &mut RawVkMemoryPriorityAllocateInfo) {
        dst.s_type = vk_to_raw_value(&VkStructureType::MemoryPriorityAllocateInfoExt);
        dst.next = ptr::null_mut();
        dst.priority = src.priority;
    }
}

impl VkRawType<VkMemoryPriorityAllocateInfo> for RawVkMemoryPriorityAllocateInfo {
    fn vk_to_wrapped(src: &RawVkMemoryPriorityAllocateInfo) -> VkMemoryPriorityAllocateInfo {
        VkMemoryPriorityAllocateInfo {
            priority: src.priority,
        }
    }
}

impl Default for VkMemoryPriorityAllocateInfo {
    fn default() -> VkMemoryPriorityAllocateInfo {
        VkMemoryPriorityAllocateInfo {
            priority: 0.0,
        }
    }
}

impl VkSetup for VkMemoryPriorityAllocateInfo {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkMemoryPriorityAllocateInfo {
    fn vk_free(&self) {
        
    }
}