// Generated by `scripts/generate.js`

pub type VkPhysicalDeviceHostQueryResetFeatures = super::super::vk::VkPhysicalDeviceHostQueryResetFeatures;

#[doc(hidden)]
pub type RawVkPhysicalDeviceHostQueryResetFeatures = super::super::vk::RawVkPhysicalDeviceHostQueryResetFeatures;