// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};

/// Wrapper for [VkPerformanceStreamMarkerInfoINTEL](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPerformanceStreamMarkerInfoINTEL.html).
#[derive(Debug, Clone)]
pub struct VkPerformanceStreamMarkerInfo {
    pub marker: usize,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkPerformanceStreamMarkerInfo {
    pub s_type: RawVkStructureType,
    pub next: *mut c_void,
    pub marker: u32,
}

impl VkWrappedType<RawVkPerformanceStreamMarkerInfo> for VkPerformanceStreamMarkerInfo {
    fn vk_to_raw(src: &VkPerformanceStreamMarkerInfo, dst: &mut RawVkPerformanceStreamMarkerInfo) {
        dst.s_type = vk_to_raw_value(&VkStructureType::PerformanceStreamMarkerInfoIntel);
        dst.next = ptr::null_mut();
        dst.marker = vk_to_raw_value(&src.marker);
    }
}

impl VkRawType<VkPerformanceStreamMarkerInfo> for RawVkPerformanceStreamMarkerInfo {
    fn vk_to_wrapped(src: &RawVkPerformanceStreamMarkerInfo) -> VkPerformanceStreamMarkerInfo {
        VkPerformanceStreamMarkerInfo {
            marker: u32::vk_to_wrapped(&src.marker),
        }
    }
}

impl Default for VkPerformanceStreamMarkerInfo {
    fn default() -> VkPerformanceStreamMarkerInfo {
        VkPerformanceStreamMarkerInfo {
            marker: 0,
        }
    }
}

impl VkSetup for VkPerformanceStreamMarkerInfo {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkPerformanceStreamMarkerInfo {
    fn vk_free(&self) {
        
    }
}