// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkAttachmentLoadOp](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkAttachmentLoadOp.html).
#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkAttachmentLoadOp {
    Load = 0,
    Clear = 1,
    DontCare = 2,
}

#[doc(hidden)]
pub type RawVkAttachmentLoadOp = i32;

impl VkWrappedType<RawVkAttachmentLoadOp> for VkAttachmentLoadOp {
    fn vk_to_raw(src: &VkAttachmentLoadOp, dst: &mut RawVkAttachmentLoadOp) {
        *dst = *src as i32
    }
}

impl VkRawType<VkAttachmentLoadOp> for RawVkAttachmentLoadOp {
    fn vk_to_wrapped(src: &RawVkAttachmentLoadOp) -> VkAttachmentLoadOp {
        unsafe {
            *((src as *const i32) as *const VkAttachmentLoadOp)
        }
    }
}

impl Default for VkAttachmentLoadOp {
    fn default() -> VkAttachmentLoadOp {
        VkAttachmentLoadOp::Load
    }
}