// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};
use vulkan::vk::{VkImageLayout,RawVkImageLayout};

/// Wrapper for [VkAttachmentDescriptionStencilLayout](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkAttachmentDescriptionStencilLayout.html).
#[derive(Debug, Clone)]
pub struct VkAttachmentDescriptionStencilLayout {
    pub stencil_initial_layout: VkImageLayout,
    pub stencil_final_layout: VkImageLayout,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkAttachmentDescriptionStencilLayout {
    pub s_type: RawVkStructureType,
    pub next: *mut c_void,
    pub stencil_initial_layout: RawVkImageLayout,
    pub stencil_final_layout: RawVkImageLayout,
}

impl VkWrappedType<RawVkAttachmentDescriptionStencilLayout> for VkAttachmentDescriptionStencilLayout {
    fn vk_to_raw(src: &VkAttachmentDescriptionStencilLayout, dst: &mut RawVkAttachmentDescriptionStencilLayout) {
        dst.s_type = vk_to_raw_value(&VkStructureType::AttachmentDescriptionStencilLayout);
        dst.next = ptr::null_mut();
        dst.stencil_initial_layout = vk_to_raw_value(&src.stencil_initial_layout);
        dst.stencil_final_layout = vk_to_raw_value(&src.stencil_final_layout);
    }
}

impl VkRawType<VkAttachmentDescriptionStencilLayout> for RawVkAttachmentDescriptionStencilLayout {
    fn vk_to_wrapped(src: &RawVkAttachmentDescriptionStencilLayout) -> VkAttachmentDescriptionStencilLayout {
        VkAttachmentDescriptionStencilLayout {
            stencil_initial_layout: RawVkImageLayout::vk_to_wrapped(&src.stencil_initial_layout),
            stencil_final_layout: RawVkImageLayout::vk_to_wrapped(&src.stencil_final_layout),
        }
    }
}

impl Default for VkAttachmentDescriptionStencilLayout {
    fn default() -> VkAttachmentDescriptionStencilLayout {
        VkAttachmentDescriptionStencilLayout {
            stencil_initial_layout: Default::default(),
            stencil_final_layout: Default::default(),
        }
    }
}

impl VkSetup for VkAttachmentDescriptionStencilLayout {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkAttachmentDescriptionStencilLayout {
    fn vk_free(&self) {
        
    }
}