// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkImageTiling](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkImageTiling.html).
#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkImageTiling {
    Optimal = 0,
    Linear = 1,
    DrmFormatModifierExt = 1000158000,
}

#[doc(hidden)]
pub type RawVkImageTiling = i32;

impl VkWrappedType<RawVkImageTiling> for VkImageTiling {
    fn vk_to_raw(src: &VkImageTiling, dst: &mut RawVkImageTiling) {
        *dst = *src as i32
    }
}

impl VkRawType<VkImageTiling> for RawVkImageTiling {
    fn vk_to_wrapped(src: &RawVkImageTiling) -> VkImageTiling {
        unsafe {
            *((src as *const i32) as *const VkImageTiling)
        }
    }
}

impl Default for VkImageTiling {
    fn default() -> VkImageTiling {
        VkImageTiling::Optimal
    }
}