// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};
use vulkan::vk::{VkDeviceMemory,RawVkDeviceMemory};

/// Wrapper for [VkMappedMemoryRange](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkMappedMemoryRange.html).
#[derive(Debug, Clone)]
pub struct VkMappedMemoryRange<'a> {
    pub memory: &'a VkDeviceMemory,
    pub offset: usize,
    pub size: usize,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkMappedMemoryRange {
    pub s_type: RawVkStructureType,
    pub next: *const c_void,
    pub memory: RawVkDeviceMemory,
    pub offset: u64,
    pub size: u64,
}

impl<'a> VkWrappedType<RawVkMappedMemoryRange> for VkMappedMemoryRange<'a> {
    fn vk_to_raw(src: &VkMappedMemoryRange, dst: &mut RawVkMappedMemoryRange) {
        dst.s_type = vk_to_raw_value(&VkStructureType::MappedMemoryRange);
        dst.next = ptr::null();
        dst.memory = vk_to_raw_value(src.memory);
        dst.offset = vk_to_raw_value(&src.offset);
        dst.size = vk_to_raw_value(&src.size);
    }
}

impl Default for VkMappedMemoryRange<'static> {
    fn default() -> VkMappedMemoryRange<'static> {
        VkMappedMemoryRange {
            memory: vk_null_ref(),
            offset: 0,
            size: 0,
        }
    }
}

impl<'a> VkSetup for VkMappedMemoryRange<'a> {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkMappedMemoryRange {
    fn vk_free(&mut self) {
        
    }
}