// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkPipelineRasterizationStateCreateFlagBits](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPipelineRasterizationStateCreateFlagBits.html)
///
/// Use the macro `VkPipelineRasterizationStateCreateFlags!` as an alternative method to create a structure. For example, these two snippets return the same value:
/// ```
/// VkPipelineRasterizationStateCreateFlags!()
/// ```
/// ```
/// VkPipelineRasterizationStateCreateFlags {
/// }
/// ```
#[derive(Debug, Clone, Copy)]
pub struct VkPipelineRasterizationStateCreateFlags {
    
}

#[doc(hidden)]
pub type RawVkPipelineRasterizationStateCreateFlags = u32;

impl VkWrappedType<RawVkPipelineRasterizationStateCreateFlags> for VkPipelineRasterizationStateCreateFlags {
    fn vk_to_raw(src: &VkPipelineRasterizationStateCreateFlags, dst: &mut RawVkPipelineRasterizationStateCreateFlags) {
        *dst = 0;
    }
}

impl VkRawType<VkPipelineRasterizationStateCreateFlags> for RawVkPipelineRasterizationStateCreateFlags {
    fn vk_to_wrapped(src: &RawVkPipelineRasterizationStateCreateFlags) -> VkPipelineRasterizationStateCreateFlags {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
}

impl Default for VkPipelineRasterizationStateCreateFlags {
    fn default() -> VkPipelineRasterizationStateCreateFlags {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
}

impl VkPipelineRasterizationStateCreateFlags {
    
    /// Return a structure with all flags to `false`.
    pub fn none() -> Self {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
    
    /// Return a structure with all flags to `true`.
    pub fn all() -> Self {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
    
    /// Return the numerical bit flags corresponding to the structure (as described in the Vulkan specs).
    pub fn to_u32(&self) -> u32 {
        0
    }
    
    /// Create a structure corresponding to the specified numerical bit flags.
    pub fn from_u32(value: u32) -> Self {
        VkPipelineRasterizationStateCreateFlags {
            
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! VkPipelineRasterizationStateCreateFlags {
    ( $( $x:ident ),* ) => {
        VkPipelineRasterizationStateCreateFlags {
            $($x: true,)*
            ..VkPipelineRasterizationStateCreateFlags::none()
        }
    }
}