// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};

/// Wrapper for [VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures.html).
#[derive(Debug, Clone)]
pub struct VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
    pub separate_depth_stencil_layouts: bool,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
    pub s_type: RawVkStructureType,
    pub next: *mut c_void,
    pub separate_depth_stencil_layouts: u32,
}

impl VkWrappedType<RawVkPhysicalDeviceSeparateDepthStencilLayoutsFeatures> for VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
    fn vk_to_raw(src: &VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures, dst: &mut RawVkPhysicalDeviceSeparateDepthStencilLayoutsFeatures) {
        dst.s_type = vk_to_raw_value(&VkStructureType::PhysicalDeviceSeparateDepthStencilLayoutsFeatures);
        dst.next = ptr::null_mut();
        dst.separate_depth_stencil_layouts = vk_to_raw_value(&src.separate_depth_stencil_layouts);
    }
}

impl VkRawType<VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures> for RawVkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
    fn vk_to_wrapped(src: &RawVkPhysicalDeviceSeparateDepthStencilLayoutsFeatures) -> VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
        VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
            separate_depth_stencil_layouts: u32::vk_to_wrapped(&src.separate_depth_stencil_layouts),
        }
    }
}

impl Default for VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
    fn default() -> VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
        VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
            separate_depth_stencil_layouts: false,
        }
    }
}

impl VkSetup for VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkPhysicalDeviceSeparateDepthStencilLayoutsFeatures {
    fn vk_free(&self) {
        
    }
}