// Generated by `scripts/generate.js`

use utils::vk_traits::*;

/// Wrapper for [VkSemaphoreCreateFlagBits](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSemaphoreCreateFlagBits.html)
#[derive(Debug, Clone, Copy)]
pub struct VkSemaphoreCreateFlags {
    
}

#[doc(hidden)]
pub type RawVkSemaphoreCreateFlags = u32;

impl VkWrappedType<RawVkSemaphoreCreateFlags> for VkSemaphoreCreateFlags {
    fn vk_to_raw(src: &VkSemaphoreCreateFlags, dst: &mut RawVkSemaphoreCreateFlags) {
        *dst = 0;
    }
}

impl VkRawType<VkSemaphoreCreateFlags> for RawVkSemaphoreCreateFlags {
    fn vk_to_wrapped(src: &RawVkSemaphoreCreateFlags) -> VkSemaphoreCreateFlags {
        VkSemaphoreCreateFlags {
            
        }
    }
}

impl Default for VkSemaphoreCreateFlags {
    fn default() -> VkSemaphoreCreateFlags {
        VkSemaphoreCreateFlags {
            
        }
    }
}

impl VkSemaphoreCreateFlags {
    
    pub fn none() -> VkSemaphoreCreateFlags {
        VkSemaphoreCreateFlags {
            
        }
    }
    
    pub fn all() -> VkSemaphoreCreateFlags {
        VkSemaphoreCreateFlags {
            
        }
    }
}

#[macro_export]
macro_rules! VkSemaphoreCreateFlags {
    ( $( $x:ident ),* ) => {
        VkSemaphoreCreateFlags {
            $($x: true,)*
            ..VkSemaphoreCreateFlags::none()
        }
    }
}

impl VkSemaphoreCreateFlags {
    
    pub fn to_u32(&self) -> u32 {
        0
    }
    
    pub fn from_u32(value: u32) -> VkSemaphoreCreateFlags {
        VkSemaphoreCreateFlags {
            
        }
    }
}