// Generated by `scripts/generate.js`

use std::os::raw::c_char;
use std::ops::Deref;
use std::ptr;
use std::cmp;
use std::mem;
use utils::c_bindings::*;
use utils::vk_convert::*;
use utils::vk_null::*;
use utils::vk_ptr::*;
use utils::vk_traits::*;
use vulkan::vk::*;
use vulkan::vk::{VkStructureType,RawVkStructureType};
use vulkan::vk::{VkSamplerYcbcrConversion,RawVkSamplerYcbcrConversion};

/// Wrapper for [VkSamplerYcbcrConversionInfo](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSamplerYcbcrConversionInfo.html).
#[derive(Debug, Clone)]
pub struct VkSamplerYcbcrConversionInfo<'a> {
    pub conversion: &'a VkSamplerYcbcrConversion,
}

#[doc(hidden)]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RawVkSamplerYcbcrConversionInfo {
    pub s_type: RawVkStructureType,
    pub next: *const c_void,
    pub conversion: RawVkSamplerYcbcrConversion,
}

impl<'a> VkWrappedType<RawVkSamplerYcbcrConversionInfo> for VkSamplerYcbcrConversionInfo<'a> {
    fn vk_to_raw(src: &VkSamplerYcbcrConversionInfo, dst: &mut RawVkSamplerYcbcrConversionInfo) {
        dst.s_type = vk_to_raw_value(&VkStructureType::SamplerYcbcrConversionInfo);
        dst.next = ptr::null();
        dst.conversion = vk_to_raw_value(src.conversion);
    }
}

impl Default for VkSamplerYcbcrConversionInfo<'static> {
    fn default() -> VkSamplerYcbcrConversionInfo<'static> {
        VkSamplerYcbcrConversionInfo {
            conversion: vk_null_ref(),
        }
    }
}

impl<'a> VkSetup for VkSamplerYcbcrConversionInfo<'a> {
    fn vk_setup(&mut self, fn_table: *mut VkFunctionTable) {
        
    }
}

impl VkFree for RawVkSamplerYcbcrConversionInfo {
    fn vk_free(&mut self) {
        
    }
}