// Generated by `scripts/generate_vk.js`

use utils::vk_traits::*;

pub type RawVkQueueGlobalPriority = i32;

#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkQueueGlobalPriority {
    Low = 128,
    Medium = 256,
    High = 512,
    Realtime = 1024,
}

impl VkRawType<VkQueueGlobalPriority> for RawVkQueueGlobalPriority {
    fn vk_to_wrapped(src: &RawVkQueueGlobalPriority) -> VkQueueGlobalPriority {
        unsafe {
            *((src as *const i32) as *const VkQueueGlobalPriority)
        }
    }
}

impl VkWrappedType<RawVkQueueGlobalPriority> for VkQueueGlobalPriority {
    fn vk_to_raw(src: &VkQueueGlobalPriority, dst: &mut RawVkQueueGlobalPriority) {
        *dst = *src as i32
    }
}

impl Default for VkQueueGlobalPriority {
    fn default() -> VkQueueGlobalPriority {
        VkQueueGlobalPriority::Low
    }
}