// Generated by `scripts/generate_vk.js`

use utils::vk_type::VkType;

pub type RawVkValidationCacheHeaderVersion = i32;

#[repr(i32)]
#[derive(Debug, PartialEq, Copy, Clone)]
pub enum VkValidationCacheHeaderVersion {
    One = 1,
}

impl VkType<RawVkValidationCacheHeaderVersion> for VkValidationCacheHeaderVersion {
    
    fn vk_to_raw(src: &VkValidationCacheHeaderVersion, dst: &mut RawVkValidationCacheHeaderVersion) {
        *dst = *src as i32
    }
    
    fn vk_from_raw(src: &RawVkValidationCacheHeaderVersion) -> VkValidationCacheHeaderVersion {
        unsafe {
            *((src as *const i32) as *const VkValidationCacheHeaderVersion)
        }
    }
    
    fn vk_default() -> VkValidationCacheHeaderVersion {
        VkValidationCacheHeaderVersion::One
    }
}