// Generated by `scripts/generate_vk.js`

use utils::vk_type::*;

pub type RawVkValidationCacheCreateFlags = u32;

#[derive(Debug, Copy, Clone)]
pub struct VkValidationCacheCreateFlags {
    
}

impl VkRawType<VkValidationCacheCreateFlags> for RawVkValidationCacheCreateFlags {
    fn vk_to_wrapped(src: &RawVkValidationCacheCreateFlags) -> VkValidationCacheCreateFlags {
        VkValidationCacheCreateFlags {
            
        }
    }
}

impl VkWrappedType<RawVkValidationCacheCreateFlags> for VkValidationCacheCreateFlags {
    fn vk_to_raw(src: &VkValidationCacheCreateFlags, dst: &mut RawVkValidationCacheCreateFlags) {
        *dst = 0;
    }
}

pub static STATIC_VK_VALIDATION_CACHE_CREATE_FLAGS : VkValidationCacheCreateFlags = VkValidationCacheCreateFlags {
    
};

impl VkDefault for VkValidationCacheCreateFlags {
    fn vk_default() -> VkValidationCacheCreateFlags {
        STATIC_VK_VALIDATION_CACHE_CREATE_FLAGS
    }
}